#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Find files with trailing whitespace
HAS_ERROR=false
for FILE in $(exec git diff-index --check --cached HEAD -- | sed '/^[+-]/d' | sed -r 's/:[0-9]+:.*//' | uniq) ; do
    echo "Error: trailing whitespace found in $FILE"
    HAS_ERROR=true
done

if [ $HAS_ERROR = true ]; then
    exit 1
fi

exit 0
